// templates/nextjs/app/page.tsx
'use client';

import React, { useState } from 'react';

export default function Home() {
  const [count, setCount] = useState(0);

  return (
    <main>
      <div className="card">
        <h1>Universal Next.js App</h1>
        <p>Scaffolded dynamically using <code>create-universal-app</code>.</p>
        <div>
          <button className="btn" onClick={() => setCount(count + 1)}>
            count is {count}
          </button>
        </div>
      </div>
    </main>
  );
}

// templates/angular/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  standalone: true,
  template: `
    <div class="card">
      <h1>Universal Angular App</h1>
      <p>Scaffolded dynamically using <code>create-universal-app</code>.</p>
      <button (click)="increment()">count is {{ count }}</button>
    </div>
  `,
})
export class AppComponent {
  count = 0;

  increment() {
    this.count++;
  }
}
