// templates/react-bare/src/App.js
import { useState } from 'react';

function App() {
  const [count, setCount] = useState(0);

  return (
    <div className="card">
      <h1>Universal Bare React App</h1>
      <p>Compiled natively using Webpack & Babel.</p>
      <button onClick={() => setCount(count + 1)}>
        count is {count}
      </button>
    </div>
  );
}

export default App;

// templates/angular/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  standalone: true,
  template: `
    <div class="card">
      <h1>Universal Angular App</h1>
      <p>Scaffolded dynamically using <code>create-universal-app</code>.</p>
      <button (click)="increment()">count is {{ count }}</button>
    </div>
  `,
})
export class AppComponent {
  count = 0;

  increment() {
    this.count++;
  }
}
